Sync documentation for Http1Builder::header_read_timeout with hyper's Builder::header_read_timeout.
hyperium/hyper-util pull request #137
Opened 2024-07-12 21:04 UTC by aaronriekenberg

I think the default of 30 seconds, and the commentary about needing to set `Timer` to avoid panics are true for `hyper_util::server::conn::auto::Builder`?

A possibly larger question - should `auto::Builder` do something to setup a `Timer` by default for http1/http2 builders?  Already `auto::Builder::new` takes an executor parameter, should this also take a timer parameter?

Thanks! 😃

2024-07-15 18:49 UTC, seanmonstar requested changes
Thanks for improving the docs! I really appreciate it <3

2024-07-15 18:49 UTC, seanmonstar commented on src/server/conn/auto.rs
> +    /// Pass `None` to disable.
Hm, I guess people _can't_ pass `None`, the argument isn't an `Option`. To allow for disabling, we'd need to change the argumenting to an `impl Into<Option<Duration>>`.

2024-07-15 18:49 UTC, seanmonstar commented on src/server/conn/auto.rs
> +    /// Default is 30 seconds.
```suggestion
    /// Default is currently 30 seconds, but do not depend on that.
```

2024-07-15 18:54 UTC, seanmonstar commented
> A possibly larger question - should auto::Builder do something to setup a Timer by default for http1/http2 builders? Already auto::Builder::new takes an executor parameter, should this also take a timer parameter?

Hm, I suppose it could be explored and if it feels better, introduced as a breaking change in `hyper-util` 0.2 or something. One additional option is making use of typestate (such as [what rustls does](https://docs.rs/rustls/latest/rustls/struct.ConfigBuilder.html#types), such that if you want to set timeout options, you have to have set a timer, but it's therefore not required if you don't need timeouts.

```rust
impl<E> Builder<E, NeedsTimer> {
    pub fn timer<T>(self, timer: T) -> Builder<E, HasTimer> {
        // ...
    }
}

impl<E> Builder<E, HasTimer> {
    pub fn http1_read_timeout(self, timeout: Duration) -> Self {
        // ...
    }
}
```

No promises that we'd do that, but if that doesn't phase you, you're welcome to explore separately and see how it goes :)

2024-07-20 18:27 UTC, aaronriekenberg commented on src/server/conn/auto.rs
> +    /// Pass `None` to disable.
Updated to use `read_timeout: impl Into<Option<Duration>>`

2024-07-20 18:31 UTC, aaronriekenberg commented
Addressed review comments.

Will take a look at using typestate separately.

Thank you!

2024-07-22 18:41 UTC, seanmonstar approved these changes

2024-07-22 22:41 UTC, merged